"""Generate the Go rule tables from the Python rule tables.

Python stays the single source of truth. This script imports ``fixpm.rules``
and ``fixpm.packages`` and emits Go source, so a rule added in
``src/fixpm/rules/*.py`` can never silently drift away from what the fast Go
probe binary knows.

    python scripts/gen_go_rules.py            # write go/rules_gen.go
    python scripts/gen_go_rules.py --check    # fail if the file is stale

Run it from anywhere; paths are resolved relative to this file.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from fixpm import __version__  # noqa: E402
from fixpm import packages as _pkg  # noqa: E402
from fixpm.rules import all_specs  # noqa: E402
from fixpm.rules.base import ManagerSpec  # noqa: E402

TARGET = ROOT / "go" / "rules_gen.go"

HEADER = """\
// Code generated by scripts/gen_go_rules.py. DO NOT EDIT.
//
// Source of truth: src/fixpm/rules/*.py and src/fixpm/packages.py.
// Regenerate with: python scripts/gen_go_rules.py

package main
"""


def go_str(value: str) -> str:
    """A Go double-quoted string literal for *value*."""
    out = ['"']
    for ch in value:
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20 or ord(ch) > 0x7E:
            if ord(ch) <= 0xFFFF:
                out.append(f"\\u{ord(ch):04x}")
            else:
                out.append(f"\\U{ord(ch):08x}")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def go_slice(values: tuple[str, ...] | list[str], indent: str) -> str:
    if not values:
        return "nil"
    items = ", ".join(go_str(v) for v in values)
    # keep generated lines readable / reviewable
    return "[]string{" + items + "}"


def go_string_map(mapping: dict[str, str], indent: str) -> str:
    if not mapping:
        return "nil"
    pairs = ", ".join(
        f"{go_str(k)}: {go_str(mapping[k])}" for k in sorted(mapping)
    )
    return "map[string]string{" + pairs + "}"


def go_slice_map(mapping: dict[str, tuple[str, ...]]) -> str:
    if not mapping:
        return "nil"
    parts = []
    for key in sorted(mapping):
        parts.append(f"\t\t{go_str(key)}: {go_slice(mapping[key], '')},")
    return "map[string][]string{\n" + "\n".join(parts) + "\n\t}"


def emit_spec(spec: ManagerSpec) -> str:
    return f"""\t{{
\t\tName:            {go_str(spec.name)},
\t\tBinaries:        {go_slice(spec.binaries, "")},
\t\tCommands:        {go_slice(spec.commands, "")},
\t\tAliases:         {go_string_map(spec.aliases, "")},
\t\tFlags:           {go_slice_map(spec.flags)},
\t\tGlobalFlags:     {go_slice(spec.global_flags, "")},
\t\tValueFlags:      {go_slice(spec.value_flags, "")},
\t\tPackageCommands: {go_slice(spec.package_commands, "")},
\t\tArgRequired:     {go_slice(spec.arg_required, "")},
\t\tTypoHints:       {go_string_map(spec.typo_hints, "")},
\t\tChains:          {go_slice_map(spec.chains)},
\t\tPackageFirst:    {"true" if spec.package_first else "false"},
\t\tSubcommandMinScore: {spec.subcommand_min_score!r},
\t}},"""


def render() -> str:
    specs = all_specs()
    blocks = "\n".join(emit_spec(s) for s in specs)
    corpus = ",\n\t".join(go_str(p) for p in _pkg.POPULAR_PACKAGES)
    return f"""{HEADER}
// version mirrors fixpm.__version__.
const version = {go_str(__version__)}

// userAgent mirrors fixpm.packages.USER_AGENT.
const userAgent = {go_str(_pkg.USER_AGENT)}

// searchURL mirrors fixpm.packages.SEARCH_URL.
const searchURL = {go_str(_pkg.SEARCH_URL)}

// downloadURL mirrors fixpm.packages.DOWNLOAD_URL.
const downloadURL = {go_str(_pkg.DOWNLOAD_URL)}

// Specs mirrors fixpm.rules.all_specs() in registration order.
var specs = []ManagerSpec{{
{blocks}
}}

// popularFallback mirrors fixpm.packages.POPULAR_FALLBACK.
var popularFallback = {go_string_map(_pkg.POPULAR_FALLBACK, "")}

// popularPackages mirrors fixpm.packages.POPULAR_PACKAGES.
var popularPackages = []string{{
\t{corpus},
}}

// corpusPopPrior mirrors fixpm.packages.CORPUS_POP_PRIOR.
const corpusPopPrior = {_pkg.CORPUS_POP_PRIOR!r}
"""


def gofmt(source: str) -> str:
    """Run the output through gofmt so --check compares formatted text.

    gofmt aligns composite-literal keys, which is not worth reimplementing in
    a string template; formatting here keeps generate/verify symmetric.
    """
    exe = shutil.which("gofmt")
    if exe is None:
        print("warning: gofmt not found; emitting unformatted Go",
              file=sys.stderr)
        return source
    # Byte mode on purpose: text mode would translate newlines on Windows and
    # desynchronise the written file from what --check compares against.
    proc = subprocess.run([exe], input=source.encode("utf-8"),
                          capture_output=True)
    if proc.returncode != 0:
        raise SystemExit(
            "gofmt failed:\n" + proc.stderr.decode("utf-8", "replace"))
    return proc.stdout.decode("utf-8").replace("\r\n", "\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the generated file is out of date")
    args = parser.parse_args()

    content = gofmt(render())
    if args.check:
        if not TARGET.exists():
            print(f"{TARGET} is missing; run scripts/gen_go_rules.py",
                  file=sys.stderr)
            return 1
        if TARGET.read_text(encoding="utf-8") != content:
            print(f"{TARGET} is stale; run scripts/gen_go_rules.py",
                  file=sys.stderr)
            return 1
        print(f"{TARGET} is up to date")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {TARGET} "
          f"({len(all_specs())} specs, "
          f"{len(_pkg.POPULAR_PACKAGES)} corpus packages, "
          f"{len(_pkg.POPULAR_FALLBACK)} curated typos)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
